---
package_source: "remote"

xroad_repo_baseurl: "https://rw3tecnologia.jfrog.io/artifactory"
xroad_repo_key:  "https://rw3tecnologia.jfrog.io/artifactory/api/security/keypair/xvia-debian-local-gpg/public"

ubuntu_apt_key:  "{{xroad_repo_key}}"
ubuntu_repo_url: "{{xroad_repo_baseurl}}/xvia-debian-local"
ubuntu_apt_repo: "deb {{ubuntu_repo_url}} {{ansible_distribution_release}}-current main"

rhel_repo_baseurl: "{{xroad_repo_baseurl}}/xvia-release-rpm/rhel/{{ansible_distribution_major_version}}/current"
rhel_repo_gpgcheck: "yes"
rhel_repo_gpgkey: "{{xroad_repo_key}}"
rhel_repo_repogpgcheck: "yes"
rhel_repo_metadataexpire: "21600"
