---
ss_modules:
  monitor:
    dir: monitor
    build: build
    lib: monitor-1.0.jar
    target: /usr/share/xroad/jlib
  proxy:
    dir: proxy
    build: build
    lib: proxy-1.0.jar
    target: /usr/share/xroad/jlib
  addon-proxy:
    dir: addons/proxymonitor/metaservice
    build: build
    lib: proxymonitor-metaservice-1.0.jar
    target: /usr/share/xroad/jlib/addon/proxy
  addon-proxy-messagelog:
    dir: addons/messagelog
    build: build
    lib: messagelog-1.0.jar
    target: /usr/share/xroad/jlib/addon/proxy
  addon-metaservice:
    dir: addons/metaservice
    build: build
    lib: metaservice-1.0.jar
    target: /usr/share/xroad/jlib/addon/proxy
  configuration-client:
    dir: configuration-client
    build: build
    lib: configuration-client-1.0.jar
    target: /usr/share/xroad/jlib
  proxy-ui-api:
    dir: security-server/admin-service/application
    build: build
    lib: proxy-ui-api-1.0.jar
    target: /usr/share/xroad/jlib
