---
# This playbook compiles X-Road and installs the compiled packages to the defined host inventory

- hosts: lxd_servers
  roles:
    - init-lxd
  tags: 
    - init

- hosts: ss_servers
  any_errors_fatal: true
  tasks:
    - name: RHEL-support check
      fail:
        msg: "Variant '{{ variant }}' does not support RHEL-servers"
      when:
        - (variant is defined and variant == "ee")
        - ansible_os_family == "RedHat"

- hosts: compile_servers
  roles:
    - compile
  tags: 
    - compile

- hosts: compile_servers
  roles:
    - build-packages
  tags:
    - build-packages
  
- hosts: ss_servers, cs_servers, cp_servers
  roles:
    - packages-to-local-repo
  tags:
    - packages

- hosts: cs_servers
  become: yes
  become_user: root
  roles:
    - xroad-cs
  tags:
    - cs
    - install
  vars_files:
    - vars_files/local_repo.yml
    - vars_files/cs_database.yml

- hosts: cp_servers
  become: yes
  become_user: root
  roles:
    - xroad-cp
  tags:
    - cp
    - install
  vars_files:
    - vars_files/local_repo.yml

- hosts: ca_servers
  become: yes
  become_user: root
  roles:
    - xroad-ca
  tags:
    - ca
    - install

- hosts: ss_servers
  become: yes
  become_user: root
  roles:
    - xroad-ss
  tags:
    - ss
    - install
  vars_files:
    - vars_files/local_repo.yml
    - vars_files/ss_database.yml
